services:

  apisix:
    image: apache/apisix:${APISIX_VERSION:-3.14.1-debian}
    restart: always
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
      - ${PWD}/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ${PWD}/config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      # Web - Proxy
      - 80:9080
      - 443:9443

  apisix_auth:
    image: apache/apisix:${APISIX_VERSION:-3.14.1-debian}
    restart: always
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
      - ${PWD}/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ${PWD}/config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      # Web - Proxy
      - 9080


  whoami:
    image: traefik/whoami:${TRAEFIK_WHOAMI_VERSION:-v1.11.0}
    ports:
      - 80

  web1:
    image: nginx:${NGINX_VERSION:-1.29.2-alpine}
    restart: always
    configs:
      - source: web1.html
        target: /usr/share/nginx/html/index.html
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80

  web2:
    image: nginx:${NGINX_VERSION:-1.29.2-alpine}
    restart: always
    configs:
      - source: web2.html
        target: /usr/share/nginx/html/index.html
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80

configs:
  web1.html:
    content: |
      <!doctype html>
      <html>
        <head>
          <title>Hello Web1</title>
          <meta charset="utf-8" />
        </head>
        <body>
          <h1>
            Hello Web1!
          </h1>
        </body>
      </html>
  web2.html:
    content: |
      <!doctype html>
      <html>
        <head>
          <title>Hello Web2</title>
          <meta charset="utf-8" />
        </head>
        <body>
          <h1>
            Hello Web2!
          </h1>
        </body>
      </html>
  default.conf:
    content: |
      server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $$uri $$uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
