apisix:
  node_listen:
    - port: 9080
  enable_ipv6: false
  enable_http2: true
  enable_control: true
  enable_server_tokens: false
  error_log:
    level: info

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

# END
